### ISSUE TITLE
License doesn't reflect the SPDX-License-Identifier

### ISSUE THREAD

**Issue by tenzap** [rpavlik/spdx-to-dep5#2]
I'm trying to extract SPDX info from files and convert to DEP5
I noticed this issue:

In source header I have:
```
// Copyright (C) 2016 Paul Lemire <paul.lemire350@gmail.com>
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0
```
summary.spdx reports:
```
FileName: ./qt3d/tests/auto/input/utils/tst_utils.cpp
SPDXID: SPDXRef-ec9701a4a6e83e5c346e9f4377005153
FileChecksum: SHA1: 78c032c19e50ba890da9609caca80ca3edea1166
LicenseConcluded: NOASSERTION
LicenseInfoInFile: GPL-3.0-only
LicenseInfoInFile: LicenseRef-Qt-Commercial
LicenseInfoInFile: Qt-GPL-exception-1.0
FileCopyrightText: <text>Copyright (C) 2016 Paul Lemire <paul.lemire350@gmail.com></text>
```

In DEP5 file there is this, which is not correct

```
Files: ./qt3d/tests/auto/input/utils/tst_utils.cpp
Copyright: 2016 Paul Lemire <paul.lemire350@gmail.com>
License: GPL-3.0-only OR LicenseRef-Qt-Commercial OR Qt-GPL-exception-1.0
```
It seems your tool always sets `OR` to join the license, while there can also be `WITH `and `AND`.

**Comment by tenzap** [comment]
Maybe related: https://github.com/fsfe/reuse-tool/issues/586

**Comment by rpavlik** [comment]
Interesting. Yeah that looks like a REUSE tool bug, because the transformation from header to spdx file is wrong (should have two lines with one being `GPL-3.0-only WITH Qt-GPL-exception-1.0`  IIUC. They have been somewhat-to-very-responsive in the past, so hopefully they look into this (or it's easy enough to fix)

(I initially thought it was the spdx-expression crate I'm using, but the .spdx file itself is wrong.)

**Comment by tenzap** [comment]
Ok. What if the relation is AND and not OR ? Would that become an OR in dep5 output?

**Comment by rpavlik** [comment]
I'm not sure a strict grammar exists for dep5 license expressions, the "with" clauses tend to concatenate the two arguments (eg gpl3-with-bison-exception)

**Comment by rpavlik** [comment]
Closing this as it's actually an issue with the input.
