### ISSUE TITLE
Allow output for empty copyright

### ISSUE THREAD

**Issue by tenzap** [rpavlik/spdx-to-dep5#4]
When there is no copyright information for a file, there is no reference to that file in the dep5 output.

Would it be possible to make that an option? So that we can have an output for all files in dept, whether they have a copyright info or not.

Maybe it could be given a value such as `_UNKNOWN_` or `_UNSPECIFIED_` or `_EMPTY_`...

**Comment by rpavlik** [comment]
sure, that seems reasonable. I was only testing on projects that already passed reuse and that I didn't want to re-do the work :)

Does reuse spdx put something in the spdx file for such files?

I don't have a ton of time to work on this project, but I'll happily review pull requests.

**Comment by rpavlik** [comment]
it's your lucky day :) I took care of a few of these wishlist items as a warmup this morning at work

**Comment by tenzap** [comment]
Thanks a lot !
