### ISSUE TITLE
improvements to filter on file extension 

### ISSUE THREAD

**Issue by tenzap** [rpavlik/spdx-to-dep5#6]
For now your code filters the files based on a few hard coded extensions.

Would it be possible to improve this with any of these suggestions?
- don't filter at all and parse all files (except spdx/reuse technical folders like `LICENSES/` `.reuse` `debian/copyright`...)
- extension exclusion filter by option as cmd line argument 
- extension inclusion by option ad cmd line argument

**Comment by rpavlik** [comment]
yeah those sound like good ideas. As you might be able to tell, this has been mostly a personal-use tool where I just monkeyed with the source to configure it for a run :) I'm sure there's a crate for command line parsing that could make it better.

**Comment by rpavlik** [comment]
Apparently I had commits locally just turning off the filter. I haven't bothered to look for Rust command line parsing crates yet, so it hasn't been configurable.
