### ISSUE TITLE
Replace space in filename by `?`

### ISSUE THREAD

**Issue by tenzap** [rpavlik/spdx-to-dep5#7]
When filename in summary.spdx contains a space, it should be replaced by a `?` character in the dep5 output file as per the dep5 spec.

Space is considered a file separator.

**Comment by rpavlik** [comment]
oh goodness sake, really? I was thinking the lines were filename separators. Weird. I guess I just avoid having spaces in source code packages.

**Comment by tenzap** [comment]
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#files-field

> The space character, used to separate patterns, cannot be escaped with a backslash. A path like "foo bar" may be selected with a pattern like "foo?bar".
